rawfile <- file("household_power_consumption.txt", "r")
cat(grep("(^Date)|(^[1|2]/2/2007)",readLines(rawfile), value=TRUE), sep="\n", file="filtered.txt")
close(rawfile)
data5row <- read.table("filtered.txt", sep = ";", header = TRUE, nrow = 5)
classes <- sapply(data5row, class)
my_data <- read.table("filtered.txt", sep = ";", header = TRUE, colClasses = classes)
png(filename = "plot1.png")
hist(my_data$Global_active_power, col = "red", xlab ="Global Active Power (kilowatts)", main = "Gobal Active Power")
dev.off()